package wanghaisheng.com.xiaoya.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CONTENT".
 */
public class Content implements java.io.Serializable {

    private Long id;
    private Integer imagewidth;
    private Integer imageheight;
    private Integer order;
    private String url;
    private String groupid;
    private String title;

    public Content() {
    }

    public Content(Long id) {
        this.id = id;
    }

    public Content(Long id, Integer imagewidth, Integer imageheight, Integer order, String url, String groupid, String title) {
        this.id = id;
        this.imagewidth = imagewidth;
        this.imageheight = imageheight;
        this.order = order;
        this.url = url;
        this.groupid = groupid;
        this.title = title;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getImagewidth() {
//        return 256;
        return imagewidth;
    }

    public void setImagewidth(Integer imagewidth) {
        this.imagewidth = imagewidth;
    }

    public Integer getImageheight() {
//        return 366;
        return imageheight;
    }

    public void setImageheight(Integer imageheight) {
        this.imageheight = imageheight;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getGroupid() {
        return groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

}
