package wanghaisheng.com.xiaoya.db;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import wanghaisheng.com.xiaoya.db.DBStoryDao;
import wanghaisheng.com.xiaoya.db.StoryCollectionDao;
import wanghaisheng.com.xiaoya.db.DBArticleDao;
import wanghaisheng.com.xiaoya.db.ArticleCollectionDao;
import wanghaisheng.com.xiaoya.db.MovieDao;
import wanghaisheng.com.xiaoya.db.MovieCollectionDao;
import wanghaisheng.com.xiaoya.db.ContentDao;
import wanghaisheng.com.xiaoya.db.GroupDao;
import wanghaisheng.com.xiaoya.db.MeituPictureDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 51): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 51;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        DBStoryDao.createTable(db, ifNotExists);
        StoryCollectionDao.createTable(db, ifNotExists);
        DBArticleDao.createTable(db, ifNotExists);
        ArticleCollectionDao.createTable(db, ifNotExists);
        MovieDao.createTable(db, ifNotExists);
        MovieCollectionDao.createTable(db, ifNotExists);
        ContentDao.createTable(db, ifNotExists);
        GroupDao.createTable(db, ifNotExists);
        MeituPictureDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        DBStoryDao.dropTable(db, ifExists);
        StoryCollectionDao.dropTable(db, ifExists);
        DBArticleDao.dropTable(db, ifExists);
        ArticleCollectionDao.dropTable(db, ifExists);
        MovieDao.dropTable(db, ifExists);
        MovieCollectionDao.dropTable(db, ifExists);
        ContentDao.dropTable(db, ifExists);
        GroupDao.dropTable(db, ifExists);
        MeituPictureDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(DBStoryDao.class);
        registerDaoClass(StoryCollectionDao.class);
        registerDaoClass(DBArticleDao.class);
        registerDaoClass(ArticleCollectionDao.class);
        registerDaoClass(MovieDao.class);
        registerDaoClass(MovieCollectionDao.class);
        registerDaoClass(ContentDao.class);
        registerDaoClass(GroupDao.class);
        registerDaoClass(MeituPictureDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
