package wanghaisheng.com.xiaoya.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DBARTICLE".
 */
public class DBArticle {

    private Long id;
    private String title;
    private String date_published;
    private String info;
    private String image;
    private String description;
    private Integer comment_count;
    private String url;
    private String channel_keys;
    private Boolean is_collected;

    public DBArticle() {
    }

    public DBArticle(Long id) {
        this.id = id;
    }

    public DBArticle(Long id, String title, String date_published, String info, String image, String description, Integer comment_count, String url, String channel_keys, Boolean is_collected) {
        this.id = id;
        this.title = title;
        this.date_published = date_published;
        this.info = info;
        this.image = image;
        this.description = description;
        this.comment_count = comment_count;
        this.url = url;
        this.channel_keys = channel_keys;
        this.is_collected = is_collected;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDate_published() {
        return date_published;
    }

    public void setDate_published(String date_published) {
        this.date_published = date_published;
    }

    public String getInfo() {
        return info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Integer getComment_count() {
        return comment_count;
    }

    public void setComment_count(Integer comment_count) {
        this.comment_count = comment_count;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getChannel_keys() {
        return channel_keys;
    }

    public void setChannel_keys(String channel_keys) {
        this.channel_keys = channel_keys;
    }

    public Boolean getIs_collected() {
        return is_collected;
    }

    public void setIs_collected(Boolean is_collected) {
        this.is_collected = is_collected;
    }

}
