package wanghaisheng.com.xiaoya.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import com.google.gson.annotations.SerializedName;

/**
 * Entity mapped to table "MEITU_PICTURE".
 */
public class MeituPicture implements java.io.Serializable {

   /* private Long id;
    private String imageId;
    private String groupId;
    private String picUrl;
    private String picPageurl;
    private Integer picHeight;
    private Integer picWidth;
    private String picSize;
    private String picTitle;
    private String picDesc;
    private String insTime;
    private Integer index;
    private String imgUrl;
    private String imgThumbUrl;
    private Integer imgThumbWidth;
    private Integer imgThumbHeight;
    private String downUrl;*/

    private Long id;
    @SerializedName("imageid")
    private String imageId;
    @SerializedName("group_id")
    private String groupId;
    @SerializedName("pic_url")
    private String picUrl;
    @SerializedName("pic_pageurl")
    private String picPageurl;
    @SerializedName("pic_height")
    private int picHeight;
    @SerializedName("pic_width")
    private int picWidth;
    @SerializedName("pic_size")
    private String picSize;
    @SerializedName("pic_title")
    private String picTitle;
    @SerializedName("pic_desc")
    private String picDesc;
    @SerializedName("ins_time")
    private String insTime;
    private int index;
    @SerializedName("qhimg_url")
    private String imgUrl;
    @SerializedName("qhimg_thumb_url")
    private String imgThumbUrl;
    @SerializedName("qhimg_thumb_width")
    private int imgThumbWidth;
    @SerializedName("qhimg_thumb_height")
    private int imgThumbHeight;
    @SerializedName("downurl")
    private String downUrl;

    public MeituPicture() {
    }

    public MeituPicture(Long id) {
        this.id = id;
    }

    public MeituPicture(Long id, String imageId, String groupId, String picUrl, String picPageurl, Integer picHeight, Integer picWidth, String picSize, String picTitle, String picDesc, String insTime, Integer index, String imgUrl, String imgThumbUrl, Integer imgThumbWidth, Integer imgThumbHeight, String downUrl) {
        this.id = id;
        this.imageId = imageId;
        this.groupId = groupId;
        this.picUrl = picUrl;
        this.picPageurl = picPageurl;
        this.picHeight = picHeight;
        this.picWidth = picWidth;
        this.picSize = picSize;
        this.picTitle = picTitle;
        this.picDesc = picDesc;
        this.insTime = insTime;
        this.index = index;
        this.imgUrl = imgUrl;
        this.imgThumbUrl = imgThumbUrl;
        this.imgThumbWidth = imgThumbWidth;
        this.imgThumbHeight = imgThumbHeight;
        this.downUrl = downUrl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImageId() {
        return imageId;
    }

    public void setImageId(String imageId) {
        this.imageId = imageId;
    }

    public String getGroupId() {
        return groupId;
    }

    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    public String getPicUrl() {
        return picUrl;
    }

    public void setPicUrl(String picUrl) {
        this.picUrl = picUrl;
    }

    public String getPicPageurl() {
        return picPageurl;
    }

    public void setPicPageurl(String picPageurl) {
        this.picPageurl = picPageurl;
    }

    public Integer getPicHeight() {
        return picHeight;
    }

    public void setPicHeight(Integer picHeight) {
        this.picHeight = picHeight;
    }

    public Integer getPicWidth() {
        return picWidth;
    }

    public void setPicWidth(Integer picWidth) {
        this.picWidth = picWidth;
    }

    public String getPicSize() {
        return picSize;
    }

    public void setPicSize(String picSize) {
        this.picSize = picSize;
    }

    public String getPicTitle() {
        return picTitle;
    }

    public void setPicTitle(String picTitle) {
        this.picTitle = picTitle;
    }

    public String getPicDesc() {
        return picDesc;
    }

    public void setPicDesc(String picDesc) {
        this.picDesc = picDesc;
    }

    public String getInsTime() {
        return insTime;
    }

    public void setInsTime(String insTime) {
        this.insTime = insTime;
    }

    public Integer getIndex() {
        return index;
    }

    public void setIndex(Integer index) {
        this.index = index;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    public String getImgThumbUrl() {
        return imgThumbUrl;
    }

    public void setImgThumbUrl(String imgThumbUrl) {
        this.imgThumbUrl = imgThumbUrl;
    }

    public Integer getImgThumbWidth() {
        return imgThumbWidth;
    }

    public void setImgThumbWidth(Integer imgThumbWidth) {
        this.imgThumbWidth = imgThumbWidth;
    }

    public Integer getImgThumbHeight() {
        return imgThumbHeight;
    }

    public void setImgThumbHeight(Integer imgThumbHeight) {
        this.imgThumbHeight = imgThumbHeight;
    }

    public String getDownUrl() {
        return downUrl;
    }

    public void setDownUrl(String downUrl) {
        this.downUrl = downUrl;
    }

}
