package wanghaisheng.com.xiaoya.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "STORY_COLLECTION".
 */
public class StoryCollection {

    private Long id;
    private String title;
    private String name;
    private String image;
    private String images;
    private String body;
    private String css;
    private Integer theme_id;
    private String share_url;

    public StoryCollection() {
    }

    public StoryCollection(Long id) {
        this.id = id;
    }

    public StoryCollection(Long id, String title, String name, String image, String images, String body, String css, Integer theme_id, String share_url) {
        this.id = id;
        this.title = title;
        this.name = name;
        this.image = image;
        this.images = images;
        this.body = body;
        this.css = css;
        this.theme_id = theme_id;
        this.share_url = share_url;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImages() {
        return images;
    }

    public void setImages(String images) {
        this.images = images;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getCss() {
        return css;
    }

    public void setCss(String css) {
        this.css = css;
    }

    public Integer getTheme_id() {
        return theme_id;
    }

    public void setTheme_id(Integer theme_id) {
        this.theme_id = theme_id;
    }

    public String getShare_url() {
        return share_url;
    }

    public void setShare_url(String share_url) {
        this.share_url = share_url;
    }

}
